title: "dev praktika: воркшопы для программистов"
lang: ru
url: https://devpraktika.ru
future: true
timezone: Europe/Moscow

collections:
  educators:
    output: true
  workshops:
    output: true

defaults:
  - scope:
      path: ""
      type: "educators"
    values:
      layout: "educator"
      permalink: /educators/:slug/
  - scope:
      path: ""
      type: "workshops"
    values:
      layout: "workshop"
      permalink: /workshops/:slug/
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "event"
      permalink: /events/:year-:month-:day-:slug/