title: "dev praktika: воркшопы для миддлов и сеньоров"
lang: ru
url: https://devpraktika.ru
future: true

collections:
  educators:
    output: true
    permalink: /educators/:title/
  workshops:
    output: true
    permalink: /workshops/:title/
  events:
    output: true
    permalink: /events/:name/

defaults:
  - scope:
      path: ""
      type: "educators"
    values:
      layout: "educator"
  - scope:
      path: ""
      type: "workshops"
    values:
      layout: "workshop"
  - scope:
      path: ""
      type: "events"
    values:
      layout: "event"